### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by supl**
This PR updates the outdated dependency NPM packages.

### CODE REVIEW

**Comment by feeblefakie** [comment]
@supl The CI is failing. PTAL!

**Comment by supl** [comment]
> @supl The CI is failing. PTAL!

@feeblefakie 
Thanks for your reminder :)
Sorry for I didn't notice it.
I re-run the pipeline and it is fine now.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

What was the issue?

**Comment by supl** [comment]
> LGTM! Thank you!
> 
> What was the issue?

@feeblefakie 
The test application can not connect to the backend Scalar DL network.
I am thinking to review it again later to see if we can find a more stable way to start the Scalar DL network.

**Pull request merged**
