### PR TITLE
Revise the example and README to use new interface

### PR DESCRIPTION
**Pull request by supl**
This PR revises the example code and README to use the new interface `execute`.

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by jnmt — COMMENTED** [review]
Overall looking good to me. `executeContract` in the table [here](https://github.com/scalar-labs/scalardl-node-client-sdk/tree/use-execute#create-clientservice-instance) should be both `execute` and `executeContract`, may be?

**Comment by supl** [comment]
> Overall looking good to me. `executeContract` in the table [here](https://github.com/scalar-labs/scalardl-node-client-sdk/tree/use-execute#create-clientservice-instance) should be both `execute` and `executeContract`, may be?

@jnmt 
Jun,
Thank you for your catch.

I revised the README in https://github.com/scalar-labs/scalardl-node-client-sdk/pull/85/commits/91d0d29defac63e969d6159ff5a3b869724f4a83

Please take a look.
Thank you!

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
